### ISSUE TITLE
Integrate with middleman-deploy

### ISSUE THREAD

**Issue by cllns** [jmmk/middleman-cloudflare_purge#1]
Hi there @jmmk! Thanks for making this gem, I'm currently using it.

Right now, I use `middleman-deploy` to deploy my site, then run `middleman cloudflare_purge`. Do you have any advice on how to automatically purge the CloudFlare cache on deploy?

**Comment by jmmk** [comment]
The easiest way is probably to make a deploy script that runs both commands

e.g.

``` bash
#!/usr/bin/env bash
set -e

echo "Deploying..."
middleman deploy

echo "Clearing cache..."
middleman cloudflare_purge

echo "Done"
```

**Comment by cllns** [comment]
K, thanks!

After making this Issue, I realized I was already using a Rakefile for different environments, so for production I added: `middleman cloudflare_purge` after the deploy
